Bill_amount=input("What is the total bill amount?\n₹")
percentage= input("what percentage of the bill would you like to tip (eg-0,1,2)?\n")
people=input("How many people you want to split bill with?\n")
fa=(float(Bill_amount)/int(people))*(1+float(percentage)/100)
print(f"each one should pay ₹{fa:.2f}")
yn=input("how many people dont have the tip amount to pay:\n")
wt=int(yn)*(float(Bill_amount)/int(people))
fa2=(float(Bill_amount)*(1+float(percentage)/100)-wt)/(int(people)-int(yn))
print(f"now each one should pay ₹{fa2:.2f}")
